<a href="https://colab.research.google.com/github/thmsfgr02/LinearAlgebra21/blob/main/Figueroa_Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE
## Laboratory 6 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

#### PRACTICE CODES for MATRIX


In [3]:
## Try out your code here.
Z=np.array([
    [3,6,9],
    [1,0,1]        
])
Z.shape

(2, 3)

In [4]:
np.transpose(Z).shape

(3, 2)

In [5]:
Z.T.shape

(3, 2)

In [6]:
ZT = Z.T
ZT

array([[3, 1],
       [6, 0],
       [9, 1]])

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [7]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [8]:
np.array_equiv(X, Y)

False

In [9]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [10]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [11]:
X @ Y

array([[3, 4],
       [2, 2]])

In [12]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In [13]:
D = np.array([
    [3,2,2],
    [3,1,3],
    [5,3,2]
])
E = np.array([
    [-2,0,5],
    [2,4,6],
    [7,4,3]
])

In [14]:
D @ E

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [15]:
D.dot(E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [16]:
np.matmul(D, E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [17]:
np.dot(D, E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [18]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [19]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [20]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [21]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [22]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [23]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [24]:
X @ Y.T

array([[13]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 