<a href="https://colab.research.google.com/github/thmsfgr02/LinearAlgebra21/blob/main/Figueroa_Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE
## Laboratory 6 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

#### PRACTICE CODES for MATRIX


In [ ]:
## Try out your code here.
Z=np.array([
    [3,6,9],
    [1,0,1]        
])
Z.shape

(2, 3)

In [ ]:
np.transpose(Z).shape

(3, 2)

In [ ]:
Z.T.shape

(3, 2)

In [ ]:
ZT = Z.T
ZT

array([[3, 1],
       [6, 0],
       [9, 1]])

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [ ]:
np.array_equiv(X, Y)

False

In [ ]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X @ Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
D = np.array([
    [3,2,2],
    [3,1,3],
    [5,3,2]
])
E = np.array([
    [-2,0,5],
    [2,4,6],
    [7,4,3]
])

In [ ]:
D @ E

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [ ]:
D.dot(E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [ ]:
np.matmul(D, E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In [ ]:
np.dot(D, E)

array([[12, 16, 33],
       [17, 16, 30],
       [10, 20, 49]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [ ]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [ ]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [ ]:
X @ Y.T

array([[13]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [2]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,1]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
A.dot(np.eye(3))

array([[3., 2., 1.],
       [4., 5., 1.],
       [1., 1., 1.]])

In [4]:
np.array_equal(A@B, B@A)

False

In [7]:
E = A @ (B @ C)
E

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [11]:
F = (A @ B) @ C
F

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [13]:
np.array_equiv(E, F)

True

In [14]:
A @ E

array([[455, 205, 368],
       [862, 385, 691],
       [211,  95, 172]])

In [15]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.array_equal(a_dot_z,z_mat)

True

In [18]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## **Determinant scalar value that is derived from a square matrix**
**Examples**

1. $$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$

2. $$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$

3. $$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

In [19]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [20]:
B = np.array([
              [1, 5, 2],
              [3, -1 ,-1],
              [0, -2, 1]
])
np.linalg.det(B)

-30.000000000000014

In [21]:
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

## **Inverse matrix is solving the problem of divisibility between matrices**

In [22]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [23]:
P = np.array([
              [6, 9, 0],
              [4, 2, -1],
              [3, 6, 7]
])
Q = np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [24]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

In [26]:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [27]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

## **Activity**

### **Task 1**
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than  (3,3) . In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [28]:
np.array([])

array([], dtype=float64)

In [29]:
A = np.array([
    [6,9,6],
    [0,4,2],
    [8,1,1]     
])

B = np.array([
    [5,2,4],
    [7,1,3],
    [5,4,4]          
])

C = np.array([
    [7,6,8],
    [1,3,4],
    [5,5,3]          

])

### **1**

In [30]:
A1 = A@B
A1

array([[123,  45,  75],
       [ 38,  12,  20],
       [ 52,  21,  39]])

In [31]:
B1 = B@A
B1

array([[62, 57, 38],
       [66, 70, 47],
       [62, 65, 42]])

In [32]:
np.array_equal(A1,B1)

False

### **2**

In [33]:
A2 = A @ (B @ C)
A2

array([[1281, 1248, 1389],
       [ 378,  364,  412],
       [ 580,  570,  617]])

In [34]:
B2 = (A @ B) @ C
B2

array([[1281, 1248, 1389],
       [ 378,  364,  412],
       [ 580,  570,  617]])

In [35]:
np.array_equal(A2,B2)

True

### **3**

In [36]:
A3 = A @ (B + C)
A3

array([[204, 138, 177],
       [ 52,  34,  42],
       [114,  77, 110]])

In [37]:
B3 = A @ B + A @ C
B3

array([[204, 138, 177],
       [ 52,  34,  42],
       [114,  77, 110]])

In [38]:
np.array_equal(A3,B3)

True

### **4**

In [39]:
A4 = (B + C) @ A
A4

array([[168, 152, 100],
       [104,  95,  63],
       [116, 133,  85]])

In [40]:
B4 = B @ A + C @ A
B4

array([[168, 152, 100],
       [104,  95,  63],
       [116, 133,  85]])

In [41]:
np.array_equal(A4,B4)

True

### **5**

In [45]:
A5 = A@B5
A5

array([[6., 9., 6.],
       [0., 4., 2.],
       [8., 1., 1.]])

In [43]:
B5 = np.eye(3)
B5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.array_equal(A5,B5)

False

### **6**

In [47]:
A6 = np.zeros(A.shape)
A6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
B6 = A.dot(np.zeros(A.shape))
B6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.array_equal(A6,B6)

True

## **Conclusion**


The Matrix and its many activities were the subject of this experiment. The Dot product was the first topic we addressed during our synchronous class; there are several techniques or codes to solve a dot product, such as utilizing the @ symbol between two variables. There are two further conditions to keep in mind while doing dot products: the first is that the inner dimensions of the two matrices must be the same, and the second is that the dot product must have specific qualities. Matrix computations by hand take a long time, however Python programming is quick and easy to code. It may also be solved with the use of techniques and a calculator. Python programming, applying shortcut techniques in manual calculations, and using calculators are all viable options for solving matrix algebra in a sensible manner.